### ISSUE TITLE
Bug in createTable()

### ISSUE THREAD

**Issue by sezruby** [SAP/kafka-connect-sap#19]
```
--- a/src/main/scala/com/sap/kafka/client/hana/HANAJdbcClient.scala
+++ b/src/main/scala/com/sap/kafka/client/hana/HANAJdbcClient.scala
@@ -188,7 +188,6 @@ case class HANAJdbcClient(hanaConfiguration: HANAConfig)  {
           throw ex
         case _ =>
           stmt.close()
-          connection.commit()
           connection.close()
       }
     }
```

This line is not necessary and it raises an exception even a table creation succeeded.
The exception can cause some consumed events to be skipped to insert.

**Comment by elakito** [comment]
I also noticed this issue when using the default setup and wondered why I had to restart the sink connector.

I think this is caused by the default autocommit mode. When I set autocommit to false in the config file with
`connection.url=jdbc:sap://..../?autocommit=false`
The error doesn't occur. I think we should change the code as suggested above and delete this commit() and  add setAutoCommit(true) within this block so that the table creation always happens with autocommit. @sbcd90 This is the same error that I mentioned to you. How do you think?

**Comment by elakito** [comment]
fixed with the linked PR.
